#!/usr/bin/env bash
prompt="device name ['l' lists]: "
lsblk
ANDROID_DEVICES="$(gio mount -li | grep activation | awk -F= '{print $2}')"
echo "$ANDROID_DEVICES" | cat
printf "\nEnsure you aren't still in the mounted device.\n"
printf "%s" "$prompt"
read -r dev
while ! [ -z "$dev" ];
do
    if [[ "$dev" == ?(-)+([0-9]) ]];
    then
	    DEVICE="$(echo $ANDROID_DEVICES | sed -n ${dev}p)"
	    if gio mount "$DEVICE"
	    then echo "$DEVICE" mounted.
		elif gio mount -u "$DEVICE"
			then echo "$DEVICE" unmounted
	    fi
    elif [ "$dev" = "l" ]; then
        lsblk
	echo $ANDROID_DEVICES | cat
    elif [ "$dev" = "q" ]; then
        exit
    else
        if grep -qs "$dev " /proc/mounts; then
            sync
            if udisksctl unmount -b /dev/"$dev"
            then
                echo "$dev" unmounted.
                if udisksctl power-off -b /dev/"$dev"
                then
                    echo "$dev" ejected.
                fi
            fi
        else
            udisksctl mount -b /dev/"$dev"
            echo "$dev" mounted to "$(lsblk -n /dev/"$dev" | rev | cut -d' ' -f1 | rev)".
        fi
    fi
    echo
    printf "%s" "$prompt"
    read -r dev
done
